### PR TITLE
Implement feature to use a TOML config file

### LINKED ISSUE #9: [Feature] Support for a TOML config file
### Description
Currently the project supports options like `-a` to specify API key, and `-u` to specify base URL. However, there's no way to change the default without modifying the code itself and rebuild.

This issue proposes a feature to support a TOML config file, in which the users can set their preferred default.

### Expected Behavoir
- The program attempts to read the config file
- If the file exists, parse it. Otherwise do nothing
- If the file can't be parsed as TOML, show error
- If any option is overridden by an argument, use the argument instead. Otherwise, use the config file content

I'd love to work on this issue myself and submit a PR for it👍

### PR DESCRIPTION
**Pull request by theoforger**
This PR will close #9.

This is a draft for the config file implementation. I'll make additional commits and we can discuss along the way.

---
Edit: The code is now ready for review 🎉 

### Behavior 
- If the config file doesn't exist, or if it's empty, load the default to the file.
- If the file exist but is not valid, program terminates with an error.
- If the file can be read, load the configurations.
- If any option is set, override the config file.

### CODE REVIEW

**Comment by theoforger** [comment]
Quick question: Do you prefer the code added to the main class file, or should I create a new one?

Thanks!

**Comment by mulla028** [comment]
If you create a separate file , would be nice

**Comment by theoforger** [comment]
The code is ready for review! Feel free to take a look. Let me know if you have any concerns or feedback 🙏

**Comment by mulla028** [comment]
Good job, code works really good 🎊 
Thank you for the contribution!

**Pull request merged**
